### ISSUE TITLE
User authentification

### ISSUE THREAD

**Issue by Kerosz** [Kerosz/biolnk#2]
**__Feature Description__**
The user must be able to authenticate and persist his session through supabase auth system.

**__Major User Stories/tasks__**
- [x] As a **user** I should see a **sign in page** so that I can **authenticate**.
- [x] As a **user** I should see a **sign up page** so that I can **create a new account**.
- [x] As a **user** I should be able to **persist my account information.**
- [ ] As a **user** I should be able to **signin using my facebook account**.
- [ ] As a **user** I should be able to **signin using my twitter account**.
- [ ] As a **user** I should be able to **signin using my google account**.
- [ ] As a **user** I should be able to **signin using a magic link**.

**__Additional Considerations__**
