### ISSUE TITLE
Biolnk app landing page

### ISSUE THREAD

**Issue by Kerosz** [Kerosz/biolnk#3]
**__Feature Description__**
The app must have a landing page to present the app mission statement and some additional information, including features and how to use the app.

**__Major User Stories/tasks__**
- [ ] As a **user** I should be able to **read the mission statement** so that I **understand the purpose of the app**.
- [ ] As a **user** I should be able to **see a list of features** so that I **understand what the app can do**.
- [ ] As a **user** I should be able to **easly find a call to action** so that I **create a new account**.
- [ ] As a **user** I should be able to **find a list with useful links** so that I **get additional information about the app**.

**__Additional Considerations__**
